version: '3.5'

services:
  zabbix-db:
    image: mysql:8.0
    container_name: zabbix-db
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - zabbix-db-storage:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -u root -proot_password" ]
      interval: 30s
      timeout: 10s
      retries: 5


  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    depends_on:
      - zabbix-server
    ports:
      - "8082:8080"

  myapp:
    image: ramazanakdag/demo
    environment:
      - JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote.ssl=false
      - Dcom.sun.management.jmxremote.authenticate=false
      - Dcom.sun.management.jmxremote.port=5000
      - Dcom.sun.management.jmxremote.rmi.port=5000
      - Dcom.sun.management.jmxremote.host=0.0.0.0
      - Djava.rmi.server.hostname=192.168.50.130
    ports:
      - "8081:8081"
      - "9001:9001"
      - "5000:5000"
    restart: always
    networks:
      - zabbix-net

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: "zabbix-agent"
      ZBX_SERVER_HOST: "zabbix-server"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge

volumes:
  zabbix-db-storage:
    driver: local


# HELLOOOOO
